version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: landingpage-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../index.html:/usr/share/nginx/html/index.html:ro
      - ../assets:/usr/share/nginx/html/assets:ro
    depends_on:
      - n8n
    restart: unless-stopped
    networks:
      - landingpage-network

  n8n:
    image: n8nio/n8n:latest
    container_name: landingpage-n8n
    ports:
      - "8080:8080"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=8080
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:8080/n8n/
      - VUE_APP_URL_BASE_API=http://localhost:8080/n8n/
      - N8N_PATH=/n8n/
      - N8N_EDITOR_BASE_URL=http://localhost:8080/n8n/
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - landingpage-network

volumes:
  n8n-data:
    driver: local

networks:
  landingpage-network:
    driver: bridge
